### ISSUE TITLE
Update readme file, development section with build and run commands.

### ISSUE THREAD

**Issue by punithmailme** [paysuper/paysuper-management-api#223]
**Is your feature request related to a problem? Please describe.**
I am a newbiee and want to see the payment-form in action, i understand this project needs to be running to see the forms in action. How to run this application?

**Describe the solution you'd like**
Kindly update the readme section on how to build and make this application up. 

**Describe alternatives you've considered**
I have not tried, since i am new to Go peoject

**Additional context**
Just like other projects of paysuper, kindly update the readme file :)

**Comment by sidmal** [comment]
Hi @punithmailme,
Thanks for feedback!

> I am a newbiee and want to see the payment-form in action, i understand this project needs to be running to see the forms in action. How to run this application?

Ok, it's not a problem, if you want just to see how work our payment form you can run payment form example in our official documentation by this link: https://docs.pay.super.com/docs/payments/#try-now.
May be you want to run payment form in your local machine? If that true I can prepare docker-compose file for run all our project localy. It's will good for you or you want to run payment form by another method (for example binary file for your OS)?

And also, of course we will update our readme, thanks :)

**Comment by punithmailme** [comment]
I was trying to run them locally. I was successfull in doing it. :) thanks.

**Comment by sidmal** [comment]
Were are you able to run payment form in local machine and I can close this issue? Or you need help with run payment form in local machine? I don't understand.
if you need help with run, can you answer to me can you run application localy use Docker?

**Comment by punithmailme** [comment]
We are good to close this :) thanks for your response and much appriciated.  !!!
